### ISSUE TITLE
.NET SDK Requirement

### ISSUE THREAD

**Issue by JustinGrote** [queil/fsc-host#10]
This is really neat, thanks.

Is there any way to host the SDK along with the application? Can a portion be shipped so as not to be so huge?

My goal is to allow for creating dynamic content in PowerShell for F# in the same way that can be done with C# with Add-Type, and for C# at least, the SDK doesn't have to be present. Ideally it all ships as a self-contained powershell module, or otherwise doesn't need to bootstrap the SDK (which is a lot when you just want some ad-hoc F# types)

https://github.com/justingrote/fsharp

This used to work but broke with the latest compiler changes disallowing dynamic compilation.

C# example I'm trying to adapt to work for F# as well:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-7.3#example-1-add-a-net-type-to-a-session

**Comment by queil** [comment]
Hi Justin,

I don't think hacking with shipping parts of the SDK with the fsc-host package promises a lot of stability or is a good practice. Although, I think it may be possible to compile without `fsc.exe` (and hence without depending on .NET SDK). The [docs](https://fsharp.github.io/fsharp-compiler-docs/fcs/compiler.html) state:
> NOTE: There are several options for hosting the F# compiler. The easiest one is to use the fsc.exe process and pass arguments.

I am wondering what the other several options are. I may give it a bit of research (any ideas welcome). However, the current version of fsc-host just assumes the SDK is there (hence my recommendation to package apps with Docker).

Side note: I guess for your use case it would be great if Powershell team could take a contrib to [Add-Type](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs) providing some guidance from the F# compiler team. From the code it looks like Add-Type is meant to support multiple langs in the future...

**Comment by queil** [comment]
Also I think [this discussion](https://github.com/dotnet/fsharp/discussions/11927) indicates the tight coupling of F# tooling with the SDK.

I'll close the issue for now.
