### ISSUE TITLE
Host project with type providers

### ISSUE THREAD

**Issue by artipo** [queil/fsc-host#5]
Hi, first of all thank you for this library, it's really great!

I'm trying to mock some project with scripting capabilities using this package, but I've run into an issue.

My host application manages a connection to a PostgreSQL database, for which I choose to use `FSharp.Data.Npgsql` type provider.
Sadly after adding this dependency to my project, the compiling of the scripts no longer works.

I get these errors:
`
["startup (1,1)-(1,1) parse error The type provider '{project_path}\bin\Debug\net5.0\FSharp.Data.Npgsql.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.Npgsql.DesignTime' which cannot be loaded from path '{project_path}\bin\Debug\net5.0\FSharp.Data.Npgsql.DesignTime.dll'. The exception reported was: System.IO.FileNotFoundException - Could not load file or assembly '{project_path}\bin\Debug\net5.0\FSharp.Data.Npgsql.DesignTime.dll'. The system cannot find the file specified.";
   "startup (1,1)-(1,1) parse warning Referenced assembly '{project_path}\bin\Debug\net5.0\FSharp.Data.Npgsql.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found"]
`

I tried to understand the issue and from what I saw it's trying to load the design time component of the type provider described by the `TypeProviderAssemblyAttribute` assembly attribute specified inside `FSharp.Data.Npgsql`.

Do you have any idea on how should I approach this?
Thank you in advance!

**Comment by queil** [comment]
@artipo does it work fine in `dotnet fsi` ? Type providers do lot of magic under the hood so I am not sure how difficult to solve the problem is. Could you add a repro so I can take a look?

**Comment by artipo** [comment]
Sure thing!

I thought it could be a `FSharp.Data.Npgsql`'s problem, so I've replicated the issue using the `JsonProvider` from `FSharp.Data`.
[#5.zip](https://github.com/queil/fsc-host/files/7575371/5.zip)

I wasn't too specific in my previous post, but the script does not use the TP directly.
I don't know if it matters, but the `FSharp.Data.Npgsql` sln has two project, with the runtime one referencing the design one.

Thank you for your time.

**Comment by queil** [comment]
You can try disabling including host entry assembly in fsc-host compiler options like:
```fsharp
    let getScriptProperties () =
      File "script.fsx"
      |> CompilerHost.getMember { Options.Default with Compiler = { Options.Default.Compiler with IncludeHostEntryAssembly = false }}
        (Member<string>.Path "Script.message")
```
Then it won't try loading the offending design time dll.

**Comment by queil** [comment]
I might consider making `false` the default as the syntax completion doesn't work very well in the script if using any assembly referenced by the host project.

**Comment by artipo** [comment]
I saw that option, sadly I cannot set it to false, since my script is designed to enable custom behavior.

I have a service defined in the host app:
```f#
type IMyService =
    abstract member GetMyObj : Guid -> Task<MyObjDto option>
    abstract member GetMyObjs : unit -> Task<MyObjDto seq>
    abstract member CreateMyObj : CreateMyObjDto -> Task<Result<MyObjDto, Error>>
```
That get used inside the script by some custom code:
```f#
let worker: Worker =
        fun (service : IMyService) logger ->
            async {
                logger.Verbose("Script worker initiated")

                [...custom code...]
            }
```

In my scenario it's not the end of the world, I can just fall back to Npgsql directly.
But not being able to use Fsc-host in conjunction with `FSharp.Data` seems a bit more concerning.

I've "solved" the syntax completion issue creating a paket references load script and by loading it during interactive only
```f#
#if INTERACTIVE
#load "./references.fsx"
#endif
```
In reality this does not works, since fsc tries to execute #load ... anyway.
So I load the script as string and then regex out that part
```f#
let scriptText = File.ReadAllText "script.fsx"

let scriptText =
    Regex.Replace(
        scriptText,
        @"#if\s+INTERACTIVE.*#endif",
        "",
        RegexOptions.Singleline
        ||| RegexOptions.IgnoreCase
    )

let export =
    scriptText
    |> Inline
    |> CompilerHost.getScriptProperty
        options
        (Property<IMyService -> ILogger -> unit Async>.Path "Script.export")
    |> Async.RunSynchronously
```

Anyway, if there is anything I can do to help in the TP issue I will gladly try to.

**Comment by queil** [comment]
Ok, I see. I've got a better understanding now. I'll need some time to play around.

> In reality this does not works, since fsc tries to execute #load ... anyway.

I guess this is a bug. I'll look into it too.

**Comment by queil** [comment]
I think we might be hitting https://github.com/fsprojects/FSharp.Data/issues/647 here.

**Comment by artipo** [comment]
Yeah, that make sense. So a workaround is to copy the .dll manually, I will give it a try.
I think the Issue can be closed, since it's obviously not yours library fault.

Either way, thank you very much!
